# title: "Jaichung Lee"
# description: "PhD Student, University of Oregon"
theme: minima

header_pages:
  - index.md
  - teaching.md
  - cv.md

# nav:
#   - title: "Home"
#     url: /
#   # - title: "Research"
#   #   url: /research
#   - title: "Teaching"
#     url: /teaching
#   - title: "CV"
#     url: /cv
  # - title: "Contact"
  #   url: /contact
